import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const src = path.join(root, "src");
const output = path.join(root, "browser", "qlik-geojson-extractor.js");

const modules = [
  "codes.js",
  "errors.js",
  "utils.js",
  "qix-client.js",
  "app-inspector.js",
  "map-inspector.js",
  "spatial-analysis.js",
  "hypercube.js",
  "geojson.js",
  "download.js",
  "extractor.js"
];

const apiNames = [
  "ERROR_CODES", "DIAGNOSTIC_CODES", "EVIDENCE_CODES", "QlikGeoJSONError", "coreError", "serializeError",
  "QixClient", "QlikGeoJSONExtractor", "coordinateWarnings", "spatialWarnings", "listAppFields", "summarizeFields", "suggestEntityKeys", "candidatePool", "scoreEntityCandidate",
  "inspectSheet", "summarizePointLayers", "walkPropertyTree", "coordinateDefinition", "analyzeCoordinateFields", "analyzeLocationField", "analyzeSpatialSource", "analyzeEntityCandidate", "spatialSourceFields",
  "buildPointCubeDefinition", "createSessionCube", "fetchAllStraightCubeRows", "propertyExpression", "normalizeMeasures", "spatialModeFromConfig",
  "rowsToPointGeoJSON", "validatePointGeoJSON", "downloadJSON", "downloadGeoJSON", "normalizeName", "qlikFieldRef",
  "qTextOrNum", "qNumOrText", "numberOrNull", "validCoordinates", "googleMapsUrl", "wazeUrl", "uniquePropertyName",
  "joinBasePath", "deepClone", "resolveSimpleQlikFieldReference", "looksLikeQlikExpression", "extractQlikFieldReferences", "parseQlikPoint"
];

function stripModuleSyntax(source) {
  return source
    .replace(/^import\s+.*?;\s*$/gm, "")
    .replace(/\bexport\s+/g, "")
    .trim();
}

const parts = modules.map((name) => {
  const source = fs.readFileSync(path.join(src, name), "utf8");
  return `// ---- src/${name} ----\n${stripModuleSyntax(source)}`;
});

const bundle = `/*\n * qlik-geojson-extractor browser bundle\n * Generated by scripts/build-browser.mjs. No runtime dependencies.\n */\n(function (global) {\n  "use strict";\n\n${parts.join("\n\n")}\n\n  global.QlikGeoJSONExtractor = Object.freeze({\n    ${apiNames.join(",\n    ")}\n  });\n})(globalThis);\n`;

fs.writeFileSync(output, bundle);
console.log(`Wrote ${path.relative(root, output)}`);
