export const ERROR_CODES = Object.freeze({
  QLIK_HOST_REQUIRED: "QLIK_HOST_REQUIRED",
  CSRF_FETCH_FAILED: "CSRF_FETCH_FAILED",
  CSRF_TOKEN_MISSING: "CSRF_TOKEN_MISSING",
  CLIENT_ALREADY_CONNECTED: "CLIENT_ALREADY_CONNECTED",
  WEBSOCKET_OPEN_FAILED: "WEBSOCKET_OPEN_FAILED",
  WEBSOCKET_NOT_OPEN: "WEBSOCKET_NOT_OPEN",
  OPENDOC_INVALID_HANDLE: "OPENDOC_INVALID_HANDLE",
  CONNECTION_CLOSED: "CONNECTION_CLOSED",
  FIELD_LIST_CREATE_FAILED: "FIELD_LIST_CREATE_FAILED",
  SHEET_GET_FAILED: "SHEET_GET_FAILED",
  PROPERTY_TREE_MISSING: "PROPERTY_TREE_MISSING",
  UNSUPPORTED_PROPERTY_AGGREGATION: "UNSUPPORTED_PROPERTY_AGGREGATION",
  SESSION_OBJECT_INVALID_HANDLE: "SESSION_OBJECT_INVALID_HANDLE",
  HYPERCUBE_LAYOUT_MISSING: "HYPERCUBE_LAYOUT_MISSING",
  LAT_LON_ATTRIBUTES_MISSING: "LAT_LON_ATTRIBUTES_MISSING",
  NULL_ENTITY_KEY: "NULL_ENTITY_KEY",
  DUPLICATE_ENTITY_KEY: "DUPLICATE_ENTITY_KEY",
  OVERRIDE_GUARD_FIELD_MISSING: "OVERRIDE_GUARD_FIELD_MISSING",
  OVERRIDE_GUARD_MISMATCH: "OVERRIDE_GUARD_MISMATCH",
  EXTRACTION_CONFIG_MISSING: "EXTRACTION_CONFIG_MISSING",
  MISSING_COORDINATES: "MISSING_COORDINATES",
  GEOJSON_VALIDATION_FAILED: "GEOJSON_VALIDATION_FAILED",
  GEOJSON_ROOT_INVALID: "GEOJSON_ROOT_INVALID",
  GEOJSON_GEOMETRY_INVALID: "GEOJSON_GEOMETRY_INVALID",
  GEOJSON_COORDINATES_INVALID: "GEOJSON_COORDINATES_INVALID",
  QIX_RPC_ERROR: "QIX_RPC_ERROR"
});

export const DIAGNOSTIC_CODES = Object.freeze({
  VISUAL_DIMENSION_LOWER_CARDINALITY: "VISUAL_DIMENSION_LOWER_CARDINALITY",
  COORDINATE_COMPLEX_EXPRESSION: "COORDINATE_COMPLEX_EXPRESSION",
  COORDINATE_RANGE_INVALID: "COORDINATE_RANGE_INVALID",
  COORDINATE_SWAP_LIKELY: "COORDINATE_SWAP_LIKELY",
  COORDINATE_STATS_UNAVAILABLE: "COORDINATE_STATS_UNAVAILABLE"
});

export const EVIDENCE_CODES = Object.freeze({
  SPATIAL_ONE_PAIR_RATIO: "SPATIAL_ONE_PAIR_RATIO",
  SPATIAL_MULTIPLE_PAIRS: "SPATIAL_MULTIPLE_PAIRS",
  SPATIAL_MISSING_COORDINATES: "SPATIAL_MISSING_COORDINATES",
  SAME_SOURCE_TABLE: "SAME_SOURCE_TABLE",
  CARDINALITY_CLOSE: "CARDINALITY_CLOSE",
  VISUAL_DIMENSION: "VISUAL_DIMENSION",
  TAG_KEY: "TAG_KEY",
  NAME_KEY_LIKE: "NAME_KEY_LIKE",
  NAME_SPATIAL_ENTITY_LIKE: "NAME_SPATIAL_ENTITY_LIKE"
});
